import "@/styles/globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { type Metadata } from "next";
// import { GeistSans } from "geist"

const GeistSans = localFont({
  src: "./GeistVF.woff2",
  variable: "--font-geist",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Sistema Administrativo: Ally Calzado",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head />
      <body className={cn("antialised min-h-screen font-sans")}>{children}
      </body>
    </html>
  );
}
